# secrets.toml
# Este archivo debe ser copiado exactamente en Streamlit Cloud > Settings > Secrets

SQLITECLOUD_CONNECTION_STRING = "sqlitecloud://cdjydgzlhk.g5.sqlite.cloud:8860/client_calendar.db?apikey=umCTRDGxAR2FUkNbpDOihf47bM4bQR3tRKJ53qFzL7A"

# Opcional: forzar entorno
KRONOS_ENV = "production"
